### ISSUE TITLE
Possibility to get all implementations from world

### ISSUE THREAD

**Issue by marigan** [Finistere/antidote#32]
It would be great to have possibility to use Lookup Pattern

Example like this

```
class Object:
  tag: str


@service
class FirstObject(Object):
  tag: str = 'first-object'


@service
class SecondObject(Object):
  tag: str = 'second-object'
```

Now it would be great to have possibility to get these services from world via:

  - 1 / by interface
            `world.get_all(Object) -> List[Object]`

  - 2 / by custom property
            `world.get_by_tag(tag = 'first-object') -> FirstObject`

  - 3 / combination
            `world.get_by_tag(tag = 'first-object', type = Object) -> Object`

**Comment by Finistere** [comment]
Hello! Your question resembles somewhat the use case of #33 if I understand it correctly. The API draft I proposed would like this for the question 1) and 2):

```python
from typing import *

from antidote import world, Plugin, service


# Used as an interface
class Object(Plugin):
    def method(self) -> Any:
        raise NotImplementedError()


# Define the qualifiers
FIRST_TAG = Object.qualifier()
SECOND_TAG = Object.qualifier()


@FIRST_TAG
@service
class FirstObject(Object):
    pass


@SECOND_TAG
@service
class SecondObject(Object):
    pass


world.get(Object.matching(FIRST_TAG))
world.get(Object.all())
```

Would something similar be adequate?

The third question is outside of the scope of this simple API. I'm considering exposing an API in the future which selects a particular implementation of an interface based on some conditions. But there isn't a lot more I can say about it currently, there's not even a draft yet.

In all cases for sure Antidote won't expose exactly the API you're suggesting. You could implement them with a [Provider](https://antidote.readthedocs.io/en/stable/extend.html) on top of `antidote.core` which is designed around flexibility. But the rest of the API (service, factories...) tries its best to favor type-safe & maintainable code. At least what I understand of it. If we take the second example `world.get_by_tag(tag = 'first-object') -> FirstObject` there are two issues for me:
- It's hard to know, statically without running the code, which objects would be returned. A string tag `'first-object'` might be used elsewhere, in comments, etc...
- There's no guarantee of even receiving an object of type `Object` / `FirstObject`. The API should guarantee it or at the very least strongly suggest it and check it at runtime.

**Comment by marigan** [comment]
Hello! This is exactly it. You proposal with tagging through qualifier is definitely more precise. Nice example of similar approach is in Angular's InjectionToken (https://angular.io/api/core/InjectionToken). However if it would be like you're proposing it would be great!!

**Comment by flisboac** [comment]
@marigan I think Angular's InjectionToken is more about name aliasing, or getting dependencies by name instead of type. It identifies one specific dependency, and acts as a substitute to a type/class when said type does not exist at runtime (which would not be the case in Python). But I like the idea of having name aliases.

**Comment by marigan** [comment]
@flisboac Yes but with generics typing is strictly typed as well. When use as `new InjectionToken<YourType>('tag')` you have all - name alias which always return `YourType` when being resolved.

**Comment by Finistere** [comment]
It took me way longer than I expected, but it's coming. :) The API would look like the following example.

```python
from antidote import implements, inject, interface, world, QualifiedBy

V1 = object()
V2 = object()


@interface
class Service:
    pass


@implements(Service).when(qualified_by=V1)
class ServiceImpl(Service):
    pass


@implements(Service).when(QualifiedBy(V2))
class ServiceImplV2(Service):
    pass


world.get[Service].single(qualified_by=V1)
world.get[Service].all()


@inject
def f(service: Service = inject.impl(QualifiedBy(V2))) -> Service:
    return service


@inject
def f(services: list[Service] = inject.impl(qualified_by=[V1, V2])) -> list[Service]:
    return services
```

The interface could also be a protocol. You have some freedom regarding the choice of qualifiers. But Antidote is using their `id`, not their equality, and it's not supporting built-in types such as strings to avoid the issue of Python "caching" strings and integers typically. Relying on a specific object should make it easier for an IDE to track what's qualified or not.

If anything doesn't feel right to you @marigan, I am all ears! I'll close the issue once it's released.
