### ISSUE TITLE
overriding gives TypeError in PyCharm

### ISSUE THREAD

**Issue by pauleveritt** [Finistere/antidote#52]
Using the example from the [overriding API reference](https://antidote.readthedocs.io/en/stable/reference/lib.html#antidote.lib.interface.interface.implements.overriding) I get the following on `BaseImpl` in `@implements(Base).overriding(BaseImpl)`:

`Expected type 'Type[Itf]', got 'Type[BaseImpl]' instead `

**Comment by Finistere** [comment]
Indeed, thanks!
Somehow `pyright` didn't catch it
