### ISSUE TITLE
mypy, cache, and interface/lazy decorators

### ISSUE THREAD

**Issue by pauleveritt** [Finistere/antidote#72]
Almost certainly a `mypy` issue.

Let's say I have this:

```python
from antidote import interface

@interface
class Greeting(Protocol):
```

I run `mypy`, it's happy. I change a docstring or comment, run again. It's unhappy:

```
error: Module not callable  [operator]
    @interface()
```

Same for `@lazy`. But if I do `rm -rf .mypy_cache/*` and run mypy again, it's happy. Until I change anything in the file.

I upgraded to latest `mypy` (as well as antidote@2.0.0b1) but no luck.

**Comment by Finistere** [comment]
It's indeed a `mypy` issue, I had the same. But it won't happen again, I've changed all modules' names to be different from the functions/objects one. It also led to issues in Sphinx.

**Comment by Finistere** [comment]
I'm closing the issue, this shouldn't happen anymore with the release `2.0.0`. Let me know if not!
